package mt.su.nrm.nginx;

/**
 * One argument of a directive, kept exactly as written ({@link #raw()}, quotes included) so
 * untouched configuration is regenerated byte for byte. {@link #value()} is the meaning: the text
 * with quotes removed.
 */
public record Arg(String raw) {

    /** The argument's value with surrounding quotes removed and quote escapes resolved. */
    public String value() {
        int n = raw.length();
        if (n >= 2) {
            char first = raw.charAt(0);
            if ((first == '"' || first == '\'') && raw.charAt(n - 1) == first && isWholeQuote(raw, first)) {
                return unescape(raw.substring(1, n - 1), first);
            }
        }
        return raw;
    }

    /** An argument for the given value, quoted only when nginx would otherwise misread it. */
    public static Arg of(String value) {
        if (!needsQuotes(value)) {
            return new Arg(value);
        }
        if (value.indexOf('"') < 0 && !endsWithBackslash(value)) {
            return new Arg("\"" + value.replace("\\", "\\\\") + "\"");
        }
        return new Arg("'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'");
    }

    private static boolean endsWithBackslash(String v) {
        return v.endsWith("\\");
    }

    private static boolean needsQuotes(String v) {
        if (v.isEmpty()) {
            return true;
        }
        char first = v.charAt(0);
        if (first == '"' || first == '\'' || first == '#' || first == '}') {
            return true;
        }
        for (int i = 0; i < v.length(); i++) {
            char c = v.charAt(i);
            if (Character.isWhitespace(c) || c == ';' || c == '{' || c == '"' || c == '\'') {
                return true;
            }
        }
        return false;
    }

    /** True if the closing quote at the end is the one that matches the opening quote. */
    private static boolean isWholeQuote(String raw, char quote) {
        for (int i = 1; i < raw.length() - 1; i++) {
            char c = raw.charAt(i);
            if (c == '\\') {
                i++;
            } else if (c == quote) {
                return false;
            }
        }
        // The last quote must not itself be escaped.
        int backslashes = 0;
        for (int i = raw.length() - 2; i > 0 && raw.charAt(i) == '\\'; i--) {
            backslashes++;
        }
        return backslashes % 2 == 0;
    }

    private static String unescape(String inner, char quote) {
        StringBuilder sb = new StringBuilder(inner.length());
        for (int i = 0; i < inner.length(); i++) {
            char c = inner.charAt(i);
            if (c == '\\' && i + 1 < inner.length()) {
                char next = inner.charAt(i + 1);
                if (next == quote || next == '\\') {
                    sb.append(next);
                    i++;
                    continue;
                }
            }
            sb.append(c);
        }
        return sb.toString();
    }

    /**
     * Splits text into arguments the way nginx reads them (quoted parts stay together) and returns
     * their values.
     */
    public static java.util.List<String> parseValues(String text) {
        java.util.List<String> values = new java.util.ArrayList<>();
        int i = 0;
        int n = text == null ? 0 : text.length();
        while (i < n) {
            while (i < n && Character.isWhitespace(text.charAt(i))) {
                i++;
            }
            if (i >= n) {
                break;
            }
            int start = i;
            while (i < n && !Character.isWhitespace(text.charAt(i))) {
                char c = text.charAt(i);
                if (c == '"' || c == '\'') {
                    i++;
                    while (i < n && text.charAt(i) != c) {
                        i += text.charAt(i) == '\\' ? 2 : 1;
                    }
                }
                i++;
            }
            values.add(new Arg(text.substring(start, Math.min(i, n))).value());
        }
        return values;
    }

    /** Joins arguments for display, keeping the quotes they were written with. */
    public static String displayJoin(java.util.List<Arg> args) {
        StringBuilder sb = new StringBuilder();
        for (Arg a : args) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append(a.raw());
        }
        return sb.toString();
    }
}
